swagger: '2.0'
info:
  version: '1.0'
  title: 'LiberBank-ApiGateway'
  description: 'LiberBank-ApiGateway definition'

definitions:

  ErrorResponse:
    type: object
    description: Tipo de error ocurrido.
    properties:
      mensaje:
        type: string
        maxLength: 250
        pattern: "[^A-Za-z0-9]"
      tipo:
        type: string
        maxLength: 250
        pattern: "[^A-Za-z0-9]"

  accountsDto:
    description: List of accounts
    type: object
    required:
    - data
    properties:
      data:
        type: array
        items:
          $ref: '#/definitions/accountDto'
      next_cursor:
        type: string
    additionalProperties: false
  accountDto:
    description: Details of an account
    type: object
    required:
    - resourceId
    - iban
    - currency
    properties:
      resourceId:
        type: string
        maxLength: 35
        description: Id account
        example: gdjg9wq1rcr8wer9mcr
      iban:
        type: string
        pattern: ^[A-Z]{2}[0-9]{22}$
        description: Used for accounts that do not have IBAN
        example: ES1720480000003400138578
      currency:
        type: string
        pattern: ^[A-Z]{3}$
        description: ISO 4217 Alpha 3
        example: EUR
      product:
        type: string
        maxLength: 20
        description: Product name of the bank for this account
        example: ACTIVA
  accountReferenceDto:
    description: Reference to an account
    type: object
    required:
    - iban
    properties:
      iban:
        type: string
        pattern: ^[A-Z]{2}[0-9]{2}[0-9]{20}$
        description: International Bank Account Number
        example: ES1720480000003400138578
      currency:
        type: string
        pattern: ^[A-Z]{3}$
        description: Badge in ISO 4217 Alpha 3
        example: EUR
  balanceDto:
    description: Information about a balance
    type: object
    required:
    - amount
    properties:
      amount:
        $ref: '#/definitions/amountDto'
        description: Amount of the balance
      lastChangeDateTime:
        type: string
        format: date
        description: Date and time of last change
        example: "2018-07-24"
  balancesDto:
    description: Description of balances shown
    type: object
    required:
    - forwardAvailable
    properties:
      closingBooked:
        $ref: '#/definitions/balanceDto'
      forwardAvailable:
        $ref: '#/definitions/balanceDto'
      retainedBalance:
        $ref: '#/definitions/balanceDto'
      openingBooked:
        $ref: '#/definitions/balanceDto'
  amountDto:
    description: Amount of an account
    type: object
    required:
    - currency
    - amount
    properties:
      currency:
        type: string
        pattern: ^[A-Z]{3}$
        description: ISO 4217 Alpha 3
        example: EUR
      amount:
        type: number
        format: decimal
        description: Quantity with fractional digits. Negative quantities begin with
          the minus sign '-'. The decimal point separator is a point'.'
  balancesResponseDto:
    description: Balance associated with an account
    type: object
    required:
    - balances
    properties:
      account:
        $ref: '#/definitions/accountReferenceDto'
      balances:
        $ref: '#/definitions/balancesDto'
  transactionDto:
    description: Information of a transaction
    type: object
    required:
    - transactionId
    - amount
    properties:
      transactionId:
        type: string
        maxLength: 9
        description: Transaction Id
        example: nfdd829qwafzx38tj9304
      entryReference:
        type: string
        maxLength: 14
        description: Transaction reference
        example: asdafw23
      bookingDate:
        type: string
        format: date
        description: Date on which an entry is registered in the bank
        example: "2017-09-21"
      amount:
        $ref: '#/definitions/amountDto'
      balances:
        $ref: '#/definitions/balancesDto'
  transactionResponseDto:
    description: Transaction associated with an account
    type: object
    properties:
      account:
        $ref: '#/definitions/accountReferenceDto'
        description: Account identifier
      transactions:
        description: Transactions processed
        type: object
        required:
        - data
        properties:
          data:
            type: array
            items:
              $ref: '#/definitions/transactionDto'
          next_cursor:
            type: string
  error:
    description: Common error response scheme
    type: object
    properties:
      error:
        type: array
        items:
          $ref: '#/definitions/errorItem'
      httpCode:
        type: string
      httpMessage:
        type: string
      moreInformation:
        type: string
    additionalProperties: false
  errorItem:
    type: object
    properties:
      code:
        type: string
      message:
        type: string
      field:
        type: string
    additionalProperties: false

  
