#Server 
server:
  port: 8020

    
# App Properties
app: 
    jwtSecret: padawansSecretKey
    jwtExpiration: 86400
    
# Mail 
spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: liberbankhackaton@gmail.com
    password: hakaton12345
    smtp:
      auth: true
      starttls:
        enable: true    