swagger: '2.0'
info:
  version: '1.0.0'
  title: Sample Implicit Flow OAuth2 Project
  description: This is an example of using OAuth2 Implicit Flow in a specification to describe security to your API.

security:
  - OAuth2: [] 
securityDefinitions:
      OAuth2:
        type: oauth2
        flow: accessCode
        authorizationUrl: https://example.com/oauth/authorize
        tokenUrl: https://example.com/oauth/token
        scopes:
          aplication: Total access 
paths:
  /login:
    post:
      summary: Login de usuario.
      description: Obtener la autorizacion para el usuario.
      produces: 
        - application/json
      consumes: 
        - application/json
      parameters:
        - name: LoginRequest
          in: body
          required: true
          schema:
            $ref: '#/definitions/LoginRequest'
      responses:
        200:
          description: OK
          schema:
            $ref: '#/definitions/LoginResponse'
  /registry:
    post:
      summary: Registrar un nuevo usuario.
      description: Registrar un nuevo usuario.
      produces: 
        - application/json
      consumes: 
        - application/json
      parameters: 
        - name: Userdata
          in: body
          required: true
          schema:
            $ref: '#/definitions/UserData'
      responses:
        201:
          description: CREATED
          schema:
            $ref: '#/definitions/MessageResponse'
    
    
    


definitions:
  
  MessageResponse:
    type: object
    properties:
      timestamp:
        type: string
      httpStatus:
        type: integer
      reasonPhrase:
        type: string
      message:
        type: string
      
  
  UserData:
    type: object
    properties:
      name:
        type: string
      surname:
        type: string
      phone:
        type: string
      email:
        type: string
      address:
        $ref: '#/definitions/Address'
      password:
        description: el password debe estar codificado haciendo uso de un sha256.
        type: string
        pattern: "[A-Fa-f0-9]{64}"
        maxLength: 64
        minLength: 64  
    
  
  LoginRequest:
    type: object
    properties:
      userName:
        description: email del usuario.
        type: string
      password:
        description: el password debe estar codificado haciendo uso de un sha256.
        type: string
        pattern: "[A-Fa-f0-9]{64}"
        maxLength: 64
        minLength: 64
  
  LoginResponse:
    type: object
    properties:
      userID:
        type: integer
        minimum: 1
        maximum: 10000
      name:
        type: string
      surname:
        type: string
      phone:
        type: string
      email:
        type: string
      address:
        $ref: '#/definitions/Address'
      products:
        type: array
        items:
          $ref: '#/definitions/Product'
      bearer:
        type: string
  Address:
    type: object
    properties:
      street:
        type: string
      country:
        type: string
      number:
        type: string
      floor:
        type: string
      postalCode:
        type: string
  
  Product:
    type: object
    properties:
      productID:
        type: integer
        minimum: 1
        maximum: 10000
      productName:
        type: string
    



# Added by API Auto Mocking Plugin
host: virtserver.swaggerhub.com
basePath: /pedrodlf/padawans-liberbank/1.0.0
schemes:
 - https